### ISSUE TITLE
SSH on another port?

### ISSUE THREAD

**Issue by tiktuk** [MisterTea/EternalTCP#10]
How do I tell `et` that I have my ssh server on another port?

**Comment by MisterTea** [comment]
The -s parameter should let you do this:

For example, if ssh is on port 1234 and you have port 5678 open:
```
et -s myhost:1234 myhost:5678
```

**Comment by tiktuk** [comment]
I tried that but I get

    et -s <host>:<port> <host>
    Pseudo-terminal will not be allocated because stdin is not a terminal.
    ssh: connect to host <host> port 22: Connection refused
    Unless you are doing development on Eternal Terminal,
    please do not call etclient directly.

(With proper values for host and port of course.)

It still tries to connect on port 22 even though another port is specified.

**Comment by MisterTea** [comment]
Ok this is fixed in cc568f73ae7eb775eca602949e126b1bc9fde04f

The correct usage is this:
```
et -s="-p 1234 myhost" myhost:5678
```

Please make the change to your launcher and let me know if it works.

**Comment by tiktuk** [comment]
Ok, thanks, it works ☺️ !

And it works correctly with iTerm2 and its tmux integration it seems, so cool! (mosh doesn't). This looks like a killer program, thank you 😄!

**Comment by MisterTea** [comment]
Thanks!  Glad you like it :-D

**Comment by daniel-centore** [comment]
I seem to be having some issues using this command line flag. Am I doing something wrong?
```
dcentore@Danylo-MBP17 ~> et --version
et version 4.1.1
dcentore@Danylo-MBP17 ~> et -s="-p 2044 daniel@127.0.0.1"  daniel@127.0.0.1
ERROR: unknown command line flag 's'
dcentore@Danylo-MBP17 ~>
```
