### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by tiktuk** [MisterTea/EternalTCP#11]
I just noticed that something was using a lot of power on my MacBook Air 11" and to my surprise it was ET:

![screen shot 2017-03-08 at 11 03 10](https://cloud.githubusercontent.com/assets/153722/23699375/37d132ac-03ef-11e7-827d-9875a82d4d0d.png)

Any ideas?

**Comment by MisterTea** [comment]
Are you running something that produces a lot of output all the time?

**Comment by tiktuk** [comment]
No, just a bash prompt.

I restarted it and now it's at around 3.4 % CPU usage which still seems a bit much but not outrageous.

**Comment by MisterTea** [comment]
Actually I see the same on my machine, I just never noticed. It shouldn't
be hard to fix.

**Comment by MisterTea** [comment]
Alright this should be fixed by 1442b56bf7ecd3c9113c12ed5b7d5d835f1c765b

Here's a mac binary, can you try this and confirm that your energy impact is reduced?

[etclient.zip](https://github.com/MisterTea/EternalTCP/files/828831/etclient.zip)

**Comment by tiktuk** [comment]
Yes, now it's at around 0.4 %, thanks so much ☺️ !
