### ISSUE TITLE
Remote forward failing under ET

### ISSUE THREAD

**Issue by tiktuk** [MisterTea/EternalTCP#15]
One of my favourite tools is [rmate](https://github.com/textmate/rmate) which can open files in TextMate 2 from an ssh session. For that to work it needs to make a remote forward. I just noticed that this fails when running under ET, even though ssh reports the forward as successful when started by ET.

(In the command below it gets the remote forward argument from `~/.ssh/config`.)

```
$ et -s="-v host " host
…
debug1: Remote connections from LOCALHOST:52698 forwarded to local address localhost:52698
…
debug1: remote forward success for: listen 52698, connect localhost:52698
debug1: All remote forwarding requests processed
…
```

Trying to open a file:

```
$ sudo rmate file.txt
/usr/local/bin/rmate: connect: Connection refused
/usr/local/bin/rmate: line 327: /dev/tcp/localhost/52698: Connection refused
Unable to connect to TextMate on localhost:52698
```

Indeed, nothing is listening:

```
$ sudo netstat -nap | grep 52698
$
```

Sorry for creating so many issues, I'm just really excited to start using ET ☺️ . My dream is to get iTerm 2 with `tmux -CC`, `rmate` and ET working together and now this is the only missing part…

**Comment by tiktuk** [comment]
Damn, I just read your How It Works-page 😟 .

> After the ETServer process begins on the server, the ssh connection closes and ssh is no longer needed.

and

> While it may be possible to implement the SSH protocol on top of ET and thus support X-forwarding and other features, it’s not implemented at the moment.

I guess I'll just need to keep a regular ssh session open for `rmate`…

**Comment by MisterTea** [comment]
Yeah, for this to work someone would have to implement ssh on top of ET.
It's not as hard as it sounds, but it's significant work.

**Comment by MisterTea** [comment]
If rmate is just a command, why not use ssh and set up a public/private key so you don't have to type your password?

**Comment by tiktuk** [comment]
Oh, I have that, but I would prefer to use ET instead of logging in every time I've lost my connection…

Which text editor do you use, if I may ask? Maybe there's something like rmate for it. It's really hard to go back after trying that ☺️.

**Comment by MisterTea** [comment]
I use emacs within tmux -CC. I also use atom with remote folders. It uses
SSH with public/private keys so you don't have to enter a password.

**Comment by tiktuk** [comment]
So you have some kind of SFTP browser inside Atom?

The cool thing about rmate is that you can open a file in one's local GUI editor from the remote ssh terminal session, just like opening emacs/vi.

It's implemented for Atom here: https://atom.io/packages/remote-atom.

I think it's really wonderful user experience ☺️ .

**Comment by MisterTea** [comment]
Yeah the remote folder thing in atom automatically reconnects so using it
with et is kind of redundant.

**Comment by tiktuk** [comment]
Ok, maybe I'll look for a similar solution ☺️ .

**Comment by MisterTea** [comment]
I'm going to close this but feel free to reopen if something comes up

**Comment by tiktuk** [comment]
Sure.

One last question though: Can't ET just keep up the ssh connection it establishes? The remote forward does indeed succeed in the first place.

**Comment by MisterTea** [comment]
For that to work, someone would have to integrate libssh or openssh into
et.
