### ISSUE TITLE
Support multiple connections on a single port

### ISSUE THREAD

**Issue by toavinaandria** [MisterTea/EternalTCP#20]
Hi,

I have the et server running on my remote host and can ssh into it (passwordless) without problems. However, if I try to run:

`et username@host` I get a permission denied.

The log file shows the following:

usr/local/bin/et: line 116:  5272 Segmentation fault: 11  $CLIENT_BINARY --passkeyfile="$TMPFILE" $VERBOSITY --host="$HOSTNAME" --port="$PORT" --log_dir="$LOG_DIR" 2> /tmp/et_err

I tried to run et -v, but there is no such verbose flag (no verbose mode showing when running with --help flag)

**Comment by MisterTea** [comment]
et -v works but logs to a file so it doesn't clobber your terminal. Can you post the client and server logs? 

To collect logs, run the following on your client:

tar -cvzPhf /tmp/etclientLogs.tar.gz /tmp/et_err /tmp/etclient.INFO

Then run this on your server:

tar -cvzPhf /tmp/etserverLogs.tar.gz /tmp/et_err /tmp/etserver.INFO

The logs will contain the IP addresses & username of the client and server, but will not contain any of the data transmitted.

**Comment by MisterTea** [comment]
f2e975b8504eb183fc047829a238793e8700c3ec updates the launcher so running et --help now shows the verbose flag.

**Comment by toavinaandria** [comment]
Thanks.

The client log is empty (both etclient.INFO and /tmp/et_err)

I cannot run the server log (permission denied) as it's being used by another user.

However, if I run the et client on my local machine with username@IPaddress, I get the following error:

/usr/local/bin/et: line 116:  4824 Segmentation fault: 11  $CLIENT_BINARY --passkeyfile="$TMPFILE" $VERBOSITY --host="$HOSTNAME" --port="$PORT" --log_dir="$LOG_DIR" 2> /tmp/et_err

**Comment by MisterTea** [comment]
Hmm, if the log is empty that may be the glog issue. What happens if you
run this:

etclient --alsologtostderr

Also what is is the client and server?

**Comment by toavinaandria** [comment]
I get the below message if I run etclient --alsologtostderr

"""Unless you are doing development on Eternal Terminal,
please do not call etclient directly.

The et launcher (run on the client) calls etclient with the correct parameters.
This ensures a secure connection.

If you intended to call etclient directly, please provide a passkey
(run "etclient --help" for details)."""

The client is MacOS Sierra and the server is running Ubuntu 16.04.1 LTS. 

Interesting thing is one colleague of mine has ET running perfectly but nobody else can get it to work.

**Comment by MisterTea** [comment]
Oh I think I know the problem.  Are you and your colleagues all trying to log into the same machine?  At the moment each person using ET needs to use their own dedicated port on the server.  It's a goofy limitation and I'm looking into softening it, but it's not obvious how to do that and clean up old sessions correctly.

**Comment by toavinaandria** [comment]
Yes we are looking to log into the same machine, so that is probably the issue.

**Comment by MisterTea** [comment]
For now you have to open up a port on the machine for each of you and you
each have to use a different port. I will fix this in the next version.

**Comment by toavinaandria** [comment]
Thank you! Very helpful

**Comment by MisterTea** [comment]
I'm doing this work in https://github.com/MisterTea/EternalTCP/tree/multiplex

I'll let you know when there's something that works.

**Comment by toavinaandria** [comment]
Thank you!

**Comment by MisterTea** [comment]
FYI: Multi user ET works now as of this commit: d971c909a7ac227b8b851746433aaff8d201baad

To use it, build this version on client and server.  Then on the server use screen/mosh and run this:
```
sudo etserver
```

And build this version on the client and use this version's launcher:
```
./launcher/et (host)
```


I still have a lot of work to do to make a real unix daemon, set up a config file, etc. etc. but I should have something more accessible in a week or so.

**Comment by MisterTea** [comment]
As of 3e9686908d64f2c9b5d9eccaefa326cc87a5598d the ET server is now a daemon (similar to sshd) and supports multiples users & connections.

**Comment by bwala-eightfold** [comment]
@MisterTea Can you help me know the documentation about how are we establishing multiple connections to remote from same local system using ssh config file
