### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by vvug** [MisterTea/EternalTCP#24]
Please package this very useful software for the Debian distribution.

**Comment by MisterTea** [comment]
How would I go about doing this? Do I email the Debian developers or
something?

**Comment by eskhool** [comment]
Did the google search for you, but I won't kid you...the process looks long, boring and intimidating but should get this awesome piece of code out there much quicker than the PPA route.

https://wiki.debian.org/DebianMentorsFaq#How_do_I_make_my_first_package.3F
https://www.debian.org/devel/wnpp/

**Comment by MisterTea** [comment]
@eskhool Thanks!  I started the process of getting a debian package: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861635

**Comment by Daniel15** [comment]
You could also host your own repo, similar to a PPA on Ubuntu. This is what we do for [Yarn](https://yarnpkg.com/) - we're using `dpkg-deb` to build the .deb file (although [fpm](https://github.com/jordansissel/fpm) is good too) and [aptly](https://www.aptly.info/) to build the repo.

**Comment by MisterTea** [comment]
Oh, nice!  I already have a deb file since that's how we make the PPA. I'll
look into aptly.

**Comment by Daniel15** [comment]
Reprepro is a bit easier to get started with, but an issue I had with it was that it only supports one version per package. Aptly lets the repo contain multiple versions of the same package, which is useful if a user wants to go back to an older version.

**Comment by Daniel15** [comment]
Reprepro is a bit easier to get started with, but an issue I had with it was that it only supports one version per package. Aptly lets the repo contain multiple versions of the same package, which is useful if a user wants to go back to an older version. For Yarn, we started with Reprepro, but migrated over to Aptly later on.

**Comment by MisterTea** [comment]
Is there something like launchpad that provides hosting for the packages?
The aptly tutorial has them hosting on S3 but I don't want to tie it to my
Amazon account if I can help it.

**Comment by Daniel15** [comment]
You can use GitHub Pages if you don't mind committing build artifacts to a repository. They're just static files. We do this for Yarn in a separate repo: https://github.com/yarnpkg/releases

**Comment by Daniel15** [comment]
Otherwise, any web hosting service that lets you upload files will do. If you've got a server somewhere, you could throw the files into a web-accessible directory :)

**Comment by MisterTea** [comment]
Hey @Daniel15 , I used aptly to create a deb repo and pushed it here: https://github.com/MisterTea/debian-et

Then I added the repo to a debian vm:
```
deb-src https://raw.githubusercontent.com/MisterTea/debian-et/master/debian-source/ unstable main
```

But I'm getting this error when I try to update:

```
W: Failed to fetch https://raw.githubusercontent.com/MisterTea/debian-et/master/debian-source/dists/unstable/main/source/Sources  Bad header line
```

Any ideas?  The URL seems to return data:

```
➜  build git:(debian) ✗ curl https://raw.githubusercontent.com/MisterTea/debian-et/master/debian-source/dists/unstable/main/source/Sources
Package: et
Binary: et
Version: 3.0.5-1
Maintainer: Jason Gauci <jgmath2000@gmail.com>
Build-Depends: debhelper (>= 9), libboost-dev, libsodium-dev, libncurses5-dev, libprotobuf-dev, protobuf-compiler, cmake, libgoogle-glog-dev, libgflags-dev, dh-systemd
Architecture: any
Standards-Version: 3.9.7
Format: 3.0 (quilt)
Directory: pool/main/e/et
Files:
 ecde24e8badf10a4bf27671a34077e73 2152 et_3.0.5-1.debian.tar.xz
 c137fdb3946d978d0c8894db0f5bbccd 1437 et_3.0.5-1.dsc
 1eb6e20c0248239187ab7da973771ef0 65140 et_3.0.5.orig.tar.gz
Checksums-Sha1:
 18e93194d234745aec7ac55b5a779a31537643ad 2152 et_3.0.5-1.debian.tar.xz
 8f763f601e5b354b76a4be4a9f020e2a5d559ef2 1437 et_3.0.5-1.dsc
 73f8bb20a71eb7359270dd2bf0d774a4ae4d8a86 65140 et_3.0.5.orig.tar.gz
Checksums-Sha256:
 673b62849e6cc00e430284ee7b03360128840b8d6ded4c389bd19ae2733fc479 2152 et_3.0.5-1.debian.tar.xz
 b8d427723c6d0fb542131ecda6b6c645951d9cfd299947efc1aecb9ebac7067d 1437 et_3.0.5-1.dsc
 19da15815f12ceaf88b152e66beb3424abf50207c2ac7680eea046eee3585cc4 65140 et_3.0.5.orig.tar.gz
Homepage: https://mistertea.github.io/EternalTCP/
Package-List:
 et deb universe/net optional arch=any
```

**Comment by Daniel15** [comment]
@MisterTea It might be serving files using the wrong content-type, or something like that. Try enabling GitHub Pages for the repository and using that rather than `raw.githubusercontent.com`. The URL will probably be something like `https://mistertea.github.io/debian-et/debian-source/`.

**Comment by MisterTea** [comment]
@Daniel15 Thank you, it worked!

**Comment by MisterTea** [comment]
There are no packages though :-(.  Possibly because I only made a source package and no binary packages

**Comment by jgallias** [comment]
Please make binary packages!
I'd love to be able to get updates via apt on my Debian systems!

**Comment by MisterTea** [comment]
@jgallias Alright I think I have something working, can you verify?

The following commands should install et on debian:

```
sudo echo "
deb https://mistertea.github.io/debian-et/debian-source/ jessie main
" >> /etc/apt/sources.list
curl -sS https://mistertea.github.io/debian-et/et.gpg | sudo apt-key add -
sudo apt update
sudo apt install et
```

**Comment by jgallias** [comment]
FYI, I just upgraded to Debian 9 Stretch

I ran:
`apt install libboost-dev libsodium-dev libncurses5-dev libprotobuf-dev protobuf-compiler cmake libgoogle-glog-dev libgflags-dev unzip wget`

then your code and got:
```
The following packages have unmet dependencies:
 et : Depends: libgflags2 but it is not installable
      Depends: libgoogle-glog0 but it is not installable
      Depends: libprotobuf9 but it is not installable
      Depends: libsodium13 (>= 0.6.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I'm noticing using apt search for each package without the number on the end, and I have a newer version of each installed:
```
libgflags2v5/stable,now 2.1.2-4 amd64 [installed]
libgoogle-glog0v5/stable,now 0.3.4-2 amd64 [installed,automatic]
libprotobuf10/stable,now 3.0.0-9 amd64 [installed,automatic]
libsodium18/stable,now 1.0.11-2 amd64 [installed,automatic]
```

Thanks.

**Comment by MisterTea** [comment]
@jgallias  ok I created debs for stretch as well.  Edit your /etc/apt/sources.list and remove the last line, then try this:

```
echo "
deb https://mistertea.github.io/debian-et/debian-source/ stretch main
" | sudo tee -a /etc/apt/sources.list
curl -sS https://mistertea.github.io/debian-et/et.gpg | sudo apt-key add -
sudo apt update
sudo apt install et
```
