### ISSUE TITLE
Ubuntu 14.04: unmet dependencies

### ISSUE THREAD

**Issue by MarkSwanson** [MisterTea/EternalTCP#29]
All of my machines are 14.04 atm.
Which Ubuntu do I need to make EternalTCP work?

The following packages have unmet dependencies:
 et : Depends: libncurses5 (>= 6) but 5.9+20140118-1ubuntu1 is to be installed
      Depends: libprotobuf9v5 but it is not installable
      Depends: libsodium18 (>= 0.6.0) but it is not installable
      Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
      Depends: libtinfo5 (>= 6) but 5.9+20140118-1ubuntu1 is to be installed
      Depends: libgflags2v5 but it is not installable
      Depends: libgoogle-glog0v5 but it is not installable

**Comment by MisterTea** [comment]
14.04 seems to be too old. Can you upgrade to the latest LTS?  I think it's
16.04

**Comment by MarkSwanson** [comment]
All of our corporate machines and VMs are still on 14.04.
No worries. 
Maybe it would help others if the docs specified Ubuntu >= 16.

**Comment by MisterTea** [comment]
I'll try to make a 14.04 build. It may be as simple as just building it
against that OS

**Comment by MisterTea** [comment]
Reopening so I can make a 14.04 build.  Going to spin up a 14.04 VM for this.

**Comment by MisterTea** [comment]
So I can't upload a PPA since ubuntu 14 doesn't have libsodium, but you can build your own using these steps:

```
sudo su -
add-apt-repository ppa:chris-lea/libsodium;
echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list;
echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list;
apt-get update
apt install libboost-dev libsodium-dev libncurses5-dev libprotobuf-dev protobuf-compiler cmake libgoogle-glog-dev libgflags-dev dh-systemd git build-essential
exit
git clone https://github.com/MisterTea/EternalTCP.git
cd EternalTCP
mkdir build
cd build
cmake ../
make
```
