### ISSUE TITLE
Seems to be a fish shell issue 

### ISSUE THREAD

**Issue by eskhool** [MisterTea/EternalTCP#30]
Expected a string, but instead found a redirection
fish: done <<< "$ET_SERVER_COMMANDS"

Setup: using ssh with a shared key from a Mac OS X Sierra installed using brew to Ubuntu server 16.04 via your ppa

Please let me know you are not able to replicate this by simply using the fish shell and I will attach the logs

**Comment by eskhool** [comment]
#25 addresses this. I guess the fix hasn't been released to the PPA/brew yet? Can we leave this open till it is released so that others may not open duplicate threads

**Comment by MisterTea** [comment]
Yep, makes sense. I plan on releasing 3.0 this week then we can close this.

**Comment by MisterTea** [comment]
3.0 is out on Ubuntu & OS/X.  Please confirm that 3.0 works for you and then close, thanks!

**Comment by eskhool** [comment]
Just FYI, the issue is resolved. Thanks!
