### ISSUE TITLE
Server Dynamic DNS Support

### ISSUE THREAD

**Issue by eskhool** [MisterTea/EternalTCP#32]
If the IP address of the server changes since the last time we connected, the new IP does not seem to get picked up.
This is especially so if I move between wireless networks where the same host may be available via different IP addresses.

What is the expected behavior of ET and can we handle the above? Thanks for looking into this

**Comment by MisterTea** [comment]
Oh interesting. I'm probably caching the IP address so I don't have to
resolve the DNS multiple times. I'll take a look at it this week.

**Comment by MisterTea** [comment]
I checked and I'm not doing any caching: every second I try to resolve the DNS from scratch.  There must be some caching at the OS level.

**Comment by MisterTea** [comment]
https://github.com/MisterTea/EternalTCP/commit/59960adacbc70211c0373ff8db8e567abae78959 should fix the issue.  Please build a new client from latest master and see if the issue is resolved, thanks.

**Comment by eskhool** [comment]
Hi, it appears that I had an aggressive local dns caching going on. It works right now without using the master. I believe we can close the issue. Whether we keep your changes or not, I am not qualified to say.
