### ISSUE TITLE
tmux control center support in VTE

### ISSUE THREAD

**Issue by jgoguen** [MisterTea/EternalTCP#33]
I have EternalTCP 3.0.2 installed on a CentOS server of mine and on my Arch laptop, using the source archive from the Github release page. After establishing a connection, I can successfully run `tmux attach`, but with the normal tmux restrictions and no scrollback. But if I run `tmux -CC attach`, I get nothing at all and the terminal hangs until I press Enter. Running `tmux -C attach` gives only this:

```
$ tmux -C attach
%begin 1494607734 1 0
%end 1494607734 1 0
%session-changed $0 0
```

There's absolutely nothing in the logs on either client or server. After some discussion, it looks like tmux's control center mode is only supported in iTerm on OS X. Having support for VTE-based terminals on Linux would be fantastic.

**Comment by jaens** [comment]
EternalTCP is just a persistent TCP forwarder and not concerned with protocol-level details, I think you want to open an issue in the repository of whatever terminal emulator you are using :)

**Comment by MisterTea** [comment]
I'm going to try to work with Hyper.js to make a replacement for tmux control mode that works on all platforms.  It sounds harder than it is:  Just implementing the control mode part of tmux would be pretty easy if I had support of a terminal emulator dev.

https://github.com/zeit/hyper/issues/1912

**Comment by MisterTea** [comment]
Closing since this requires a terminal emulator that is interested.
