### ISSUE TITLE
failure to connect

### ISSUE THREAD

**Issue by nresare** [MisterTea/EternalTCP#34]
Recently et began failing to connect. After authenticating over ssh I started getting the error
`Could not make initial connection to nresare.sb.facebook.com: Could not connect to host` when invoking `et -v nresare.sb.facebook.com:8080`.

What I have done to attempt to resolve the situation:

* Ran 'brew upgrade et'. This compiled and installed version 3.0.0
* Verified that a recent version of eternalterminal was installed on the server side: 
`rpm -q eternalterminal` outputs `eternalterminal-3.0.2-1.el7.centos.x86_64`
* After re-running after upgrade the failure now looks like this:
```
/usr/local/bin/et: line 97:  3159 Abort trap: 6           $CLIENT_BINARY --idpasskeyfile="$TMPFILE" $VERBOSITY --host="$HOSTNAME" --port="$PORT" --log_dir="$LOG_DIR" 2> /tmp/etclient_err
tar -cvzPhf /tmp/etclientLogs.tar.gz /tmp/et_err /tmp/etclient.INFO
$ cat /tmp/etclient_err
F0518 15:15:26.876054 3090506688 TerminalClient.cpp:61] Invalid idPasskey id/key pair:
*** Check failure stack trace: ***
    @        0x10e4890ce  google::LogMessage::Fail()
    @        0x10e4883ad  google::LogMessage::SendToLog()
    @        0x10e488ab3  google::LogMessage::Flush()
    @        0x10e48bd03  google::LogMessageFatal::~LogMessageFatal()
    @        0x10e4893b7  google::LogMessageFatal::~LogMessageFatal()
    @        0x10e258b84  main
    @     0x7fffaf444235  start
```
There is no meaningful debug output that I can find on the server side.

**Comment by MisterTea** [comment]
Can you verify that the server is running?  What happens when you do this
on the server:

systemctl status et

**Comment by nresare** [comment]
systemctl status et revealed that the server component was indeed dead "Active: inactive (dead)" and after having run `systemctl start et` as root I can now connect with et again.

Thanks for the friendly hint.
