### ISSUE TITLE
Won't connect

### ISSUE THREAD

**Issue by jasonehines** [MisterTea/EternalTCP#35]
I've installed it on an Ubuntu 17.04 server and Solus 2017.04.18.0
by compiling. On the server I opened port 2022 and restarted the firewall.  I ran `sudo etserver` and the server says `waiting for connection`. When I run `et -v www.myserver.com` I'm returned to the prompt after about 7 seconds. The server returns `Credentials from SO_PEERCRED: pid=10999, euid=1001, egid=1001` and then goes back to `waiting for connection`.  The only thing that shows in `etclient_err` is `ERROR: unknown command line flag 'log_dir'
ERROR: unknown command line flag 'v'`

I'm not sure what else to try. There is nothing in the journal on either system. Any ideas?

**Comment by jasonehines** [comment]
I deleted the binaries on both systems and then compiled 3.0.5 and 3.0.4 on both system and the results are the same.

**Comment by MisterTea** [comment]
Yep, this is because you built glog without gflags support.  Please use the glog that came with ubuntu or build glog with gflags support.

**Comment by jasonehines** [comment]
I didn't build glog.

**Comment by MisterTea** [comment]
What OS?  Ubuntu and osx definitely build glog with gflags support

**Comment by jasonehines** [comment]
I'm running Solus. One of the devs just rebuilt the package and I tested and it works now.
