### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by jasonehines** [MisterTea/EternalTCP#36]
How do you disconnect from the session without killing it?

**Comment by MisterTea** [comment]
I'm not sure I understand the question. If you lose Internet, the ET
session stays alive until you regain a connection. Are you asking if
there's a way to kill ET and then restart it where it left off?  What's the
use case for that?

**Comment by jasonehines** [comment]
Say for example I need to shutdown my computer or my battery runs out. If I close the terminal window, and run et again, I get a new pty.

How can I reconnect to that same session?

**Comment by jasonehines** [comment]
Actually I'm not sure it's working at all. I connected to my server, ran a count script, disconnected my wifi, reconnected and it never resumes.

Here are the logs:
[etclientLogs.tar.gz](https://github.com/MisterTea/EternalTCP/files/1062050/etclientLogs.tar.gz)
[etserverLogs.tar.gz](https://github.com/MisterTea/EternalTCP/files/1062049/etserverLogs.tar.gz)

FYI, there's two typo's in the new issue instructions. 
this `tar -cvzPhf /tmp/etclientLogs.tar.gz /tmp/et_err /tmp/etclient.INFO`
should be this `tar -cvzPhf /tmp/etclientLogs.tar.gz /tmp/etclient_err /tmp/etclient.INFO`
and this `tar -cvzPhf /tmp/etserverLogs.tar.gz /tmp/et_err /tmp/etserver.INFO`
should be this `tar -cvzPhf /tmp/etserverLogs.tar.gz /tmp/etserver_err /tmp/etserver.INFO`

**Comment by MisterTea** [comment]
Thanks @jasonehines , can you edit the issue template and make the changes? https://github.com/MisterTea/EternalTCP/blob/master/.github/ISSUE_TEMPLATE.md

Also, what OS is the client and server?

**Comment by jasonehines** [comment]
The server is Ubuntu 17.04. The client is [Solus](https://solus-project.com/) 2017.04.18.0

**Comment by MisterTea** [comment]
Hmm, it's definitely a client error.  The relevant line in the log is this:

```
E0608 14:38:23.065757  9054 UnixSocketHandler.cpp:93] Error getting address info for ...: -3 (Temporary failure in name resolution)
```

This repeats and never ends meaning the client can't resolve the DNS entry after a disconnect.  Strange.  Maybe adding a delay will help.  Please try this branch on your client and see if it fixes the problem: https://github.com/MisterTea/EternalTCP/tree/issue_36

**Comment by jasonehines** [comment]
That worked. I was able to disconnect my wifi and my session continued with I reestablished the wifi.

**Comment by jasonehines** [comment]
I spoke too soon. I guess I should have disconnected longer the first time. I tried again and got this message: `/usr/local/bin/et: line 114: 25671 Segmentation fault      $CLIENT_BINARY --idpasskeyfile="$TMPFILE" $VERBOSITY --host="$HOSTNAME" --port="$PORT" --log_dir="$LOG_DIR" 2> /tmp/etclient_err
                                                       %                                                                            `

Here's the error log: 
[etclientLogs.tar.gz](https://github.com/MisterTea/EternalTCP/files/1086161/etclientLogs.tar.gz)

**Comment by MisterTea** [comment]
ugh, segfault.  Can you run under gdb and get the stack trace?

run cmake with the -DCMAKE_BUILD_TYPE=Debug argument, then run the client
under gdb.  You will likely have to edit the et file to use gdb.

**Comment by MisterTea** [comment]
Another thing that is easier is to run in verbose mode by passing the -v flag to et.  I may be able to figure out the crash from the verbose logs.

**Comment by jasonehines** [comment]
I've never used gdb, I'll try and figure it out. I was running `et -v` that's all that showed in the log.

**Comment by jasonehines** [comment]
I redid the build with the debug option but when I run `gdb et` it says `"/usr/local/bin/et": not in executable format: File format not recognized`. I'm not sure what you meant above about editing the et file.

**Comment by MisterTea** [comment]
the et file is just a bash script.  You will have to edit that bash script
and change this line:

CLIENT_BINARY="etclient"

to this:

CLIENT_BINARY="gdb --args etclient"

**Comment by jasonehines** [comment]
I have no idea if I'm doing this correctly but here's the output:
[gdb-et-output.txt](https://github.com/MisterTea/EternalTCP/files/1092537/gdb-et-output.txt)

**Comment by MisterTea** [comment]
Hey, this was right, but when it crashed, you needed to type "bt" at the
prompt to get the backtrace.  Please do that and send me the backtrace so I
can debug, thanks.

**Comment by jasonehines** [comment]
glad I left it open. Here it is with the backtrace:
[gdb-et-output.txt](https://github.com/MisterTea/EternalTCP/files/1092548/gdb-et-output.txt)

**Comment by MisterTea** [comment]
Alright, I fixed that problem in the latest commit.  Please update your branch and try again.

**Comment by jasonehines** [comment]
It didn't crash this time. But it never reconnected. This is what the log is saying `UnixSocketHandler.cpp:96] Error getting address info for drive.hinesnetwork.com:2022: -3 (Temporary failure in name resolution)
`

**Comment by MisterTea** [comment]
Oh I found this that may be related: https://sourceware.org/bugzilla/show_bug.cgi?id=12224

**Comment by MisterTea** [comment]
Alright I added a call to res_init() before calling getaddrinfo.  Please update your branch and try again

**Comment by jasonehines** [comment]
it works!

**Comment by MisterTea** [comment]
Great!  Thanks for your patience
