### ISSUE TITLE
Add support for chaining the ssh command

### ISSUE THREAD

**Issue by Yostage** [MisterTea/EternalTCP#38]
I can automatically reconnect to tmux with one command by using:
`ssh <host> -t -- tmux -uCC new -s <session name> -AD`

If we had some kind of comparable -t command to et, we could use the same alias for et.

**Comment by MisterTea** [comment]
I'm not sure entirely what -t does, but I am going to implement the equivalent to -c.  So you will be able to do:
```
et <host> -c "echo hello world"
```

**Comment by MisterTea** [comment]
If you build latest master on your client pc, you should be able to use this:
et -c "echo hi; echo hi" <host>

**Comment by burgalon** [comment]
i'm using `etclient version 4.0.5` on Mac, and for some reason the `-c` chaining is not working. Any ideas?
```
➜  ~ et -c "echo hi; echo hi" ubuntu@servername


➜  ~
```

**Comment by timotheecour** [comment]
> I'm not sure entirely what -t does

see https://github.com/MisterTea/EternalTerminal/issues/620
