### ISSUE TITLE
Does not work for Ubuntu 16.04.2

### ISSUE THREAD

**Issue by GasCreature** [MisterTea/EternalTCP#42]
Installed on Mac and on Ubuntu 16.04.2 and could not connect from Mac to Ubuntu. I got hung terminals which I closed.

If on Ubuntu, could connect to the same machine at localhost but it was very slow.

**Comment by MisterTea** [comment]
Please attach the logs as instructed by the issue template, thanks.

**Comment by GasCreature** [comment]
The original logs showed a mess of timeouts and port not availables. After I uninstalled and reinstalled both sides, thing worked now.
