### ISSUE TITLE
Cannot open your terminal '/dev/pts/3' - please check.

### ISSUE THREAD

**Issue by thirdreplicator** [MisterTea/EternalTCP#47]
If you have set up ET correctly and are having an issue connecting/maintaining a session, please consider running in verbose mode and adding client & server logs to your issue.

To run in verbose mode, pass the -v flag to et.

To collect logs, run the following on your client:

tar -cvzPhf /tmp/etclientLogs.tar.gz /tmp/etclient_err /tmp/etclient.INFO

Then run this on your server:

tar -cvzPhf /tmp/etserverLogs.tar.gz /tmp/etserver_err /tmp/etserver.INFO

The logs will contain the IP addresses & username of the client and server, but will not contain any of the data transmitted.

If you are experiencing a crash, please also post a backtrace.  To do this, replace this line in your et script:

CLIENT_BINARY="etclient"

to this:

CLIENT_BINARY="lldb -- etclient"

then rerun with lldb and when it crashes, type "bt" to give me the stack trace.  If you are running the client under linux, replace with:

CLIENT_BINARY="gdb --args etclient"

**Comment by thirdreplicator** [comment]
I usually use UNIX screen, but after logging into the server and invoking:

  screen -xR

The screen session doesn't start, and I get the following error:

  Cannot open your terminal '/dev/pts/3' - please check.

**Comment by MisterTea** [comment]
What OS?  What version of ET?

**Comment by thirdreplicator** [comment]
Mac OS Sierra

I just did:

brew install MisterTea/et/et

then logged into Ubuntu 16.04

I'm not at the computer now, but I'll give you the exact versions later.
Hopefully, what I've given above is helpful.

**Comment by MisterTea** [comment]
does it work fine with ssh?

**Comment by thirdreplicator** [comment]
Sorry, I'm not sure what you mean by "does it work fine with ssh?".  Here
is what I do normally:

### Without "et":

>>> ssh me@myserver.com  # at Mac OS X terminal (10.12.5 (16F73))

Last login: Tue Jul  4 22:59:43 UTC 2017 from 67.164.84.183 on pts/0
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.9.15-x86_64-linode81 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

60 packages can be updated.
13 updates are security updates.

No mail.

$ screen -xR

# Okay now I'm in my screen session.

### Now with "et":

>>> et me@myserver.com

tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified

$ screen -xR
Cannot open your terminal '/dev/pts/5' - please check.
$

Hope this helps.

**Comment by thirdreplicator** [comment]
Here is my version of et:

brew info MisterTea/et/et
mistertea/et/et: stable 3.1.0
Remote terminal with IP roaming
https://mistertea.github.io/EternalTCP/
/usr/local/Cellar/et/3.1.0 (9 files, 601.0KB) *
  Built from source on 2017-06-29 at 20:12:53
From: https://github.com/MisterTea/homebrew-et/blob/master/et.rb
==> Dependencies
Build: cmake ✔
Required: protobuf ✔, libsodium ✔, glog ✔, gflags ✔, boost ✔
==> Caveats
To have launchd start mistertea/et/et now and restart at startup:
  sudo brew services start mistertea/et/et

**Comment by thirdreplicator** [comment]
Here is my version of et:

brew info MisterTea/et/et
mistertea/et/et: stable 3.1.0
Remote terminal with IP roaming
https://mistertea.github.io/EternalTCP/
/usr/local/Cellar/et/3.1.0 (9 files, 601.0KB) *
  Built from source on 2017-06-29 at 20:12:53
From: https://github.com/MisterTea/homebrew-et/blob/master/et.rb
==> Dependencies
Build: cmake ✔
Required: protobuf ✔, libsodium ✔, glog ✔, gflags ✔, boost ✔
==> Caveats
To have launchd start mistertea/et/et now and restart at startup:
  sudo brew services start mistertea/et/et

**Comment by MisterTea** [comment]
What version of ET on the server?

Can you tell me the output of:

systemctl status et

**Comment by MisterTea** [comment]
Also it may be that screens you create in ssh can't be resumed in et and vice versa

**Comment by thirdreplicator** [comment]
systemctl status et
● et.service - Eternal Terminal
   Loaded: loaded (/lib/systemd/system/et.service; enabled; vendor preset:
enabled)
   Active: active (running) since Fri 2017-06-30 03:16:03 UTC; 5 days ago
  Process: 32612 ExecStart=/usr/bin/etserver --daemon --cfgfile=/etc/et.cfg
(code=ex
 Main PID: 32613 (etserver)
   CGroup: /system.slice/et.service
           ├─17427 /bin/bash --login
           └─32613 /usr/bin/etserver --daemon --cfgfile=/etc/et.cfg

**Comment by thirdreplicator** [comment]
I terminated my existing session, exited back to Mac OS X, then initiated

et me@myserver.com

Then when back on Ubuntu (server), I tried to start up a new screen session.

$ screen -xR

Cannot open your terminal '/dev/pts/2' - please check.

Same error, but now it's saying /dev/pts/2 ... not sure why the number
changed.  (Maybe it's because I'm on a VPS at Linode? )

**Comment by MisterTea** [comment]
What version of et are you running on the server?

apt-cache policy et

^ That should tell us.

**Comment by MisterTea** [comment]
Also what happens if you just run "screen" by itself?  I don't know what -xR are doing?

**Comment by thirdreplicator** [comment]
On the server:

$ apt-cache policy et

et:

  Installed: 3.0.5-1ubuntu1

  Candidate: 3.1.0-xenial2

  Version table:

     3.1.0-xenial2 500

        500 http://ppa.launchpad.net/jgmath2000/et/ubuntu xenial/main amd64
Packages

 *** 3.0.5-1ubuntu1 100

        100 /var/lib/dpkg/status

**Comment by thirdreplicator** [comment]
Also on the server:


$ screen

Cannot open your terminal '/dev/pts/2' - please check.

**Comment by thirdreplicator** [comment]
When I type just "screen" on the server, I get the same error.  "Cannot
open your terminal '/dev/pts/2' - please check.

**Comment by MisterTea** [comment]
Gotcha.  I can replicate the issue on my machine.  I'll debug, but in the meantime you should switch to tmux which is way better :-)

**Comment by thirdreplicator** [comment]
How do I switch to tmux?  What is tmux, sorry for the newbie question.

**Comment by MisterTea** [comment]
tmux is similar to screen but more modern.  If you update the server to latest master, the issue is fixed.  The fix will go out in the next version.

**Comment by thirdreplicator** [comment]
Awesome.  Thanks.  Looking forward to using it.

Tc.

**Comment by MisterTea** [comment]
Fixed in version 3.3.1, apt update + apt upgrade to get the fix.
