### ISSUE TITLE
Improve documentation for using custom ssh commands.

### ISSUE THREAD

**Issue by mbtamuli** [MisterTea/EternalTCP#48]
My server listens on port `2222` instead of the standard `22`.
```
mbtamuli@nyc-512mb ~ » sudo ufw status numbered
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 22                         DENY IN     Anywhere                  
[ 2] 2222                       ALLOW IN    Anywhere                  
[ 3] 2022                       ALLOW IN    Anywhere                  
[ 4] 22 (v6)                    DENY IN     Anywhere (v6)             
[ 5] 2222 (v6)                  ALLOW IN    Anywhere (v6)             
[ 6] 2022 (v6)                  ALLOW IN    Anywhere (v6)             
```
I opened the `2022` port for et. Still I am not able to connect. (I already have open `2222`)
```
$ et mbtamuli@example.com:2222
ssh: connect to host techfreak.ga port 22: Connection timed out
SSH handshake failed.
```

I can confirm it's working perfectly fine for my other server which is listening on the standard SSH port `22`

**Comment by MisterTea** [comment]
Et and ssh run on different ports. To change the ssh port, you need to pass
a flag to ssh itself using the -s command.

**Comment by mbtamuli** [comment]
Can you please describe how to do that? It doesn't seem to be documented. I tried reading the launcher to figure it out, but from what I could see, the `et` bash launcher sends the port specified at the end of the whole command to the. The `:2222` at the end(As per line [#79](https://github.com/MisterTea/EternalTCP/blob/master/launcher/et#L79)). I may be wrong.

I've tried the following commands.
```
$ et -s="mbtamuli@example.com:2222" mbtamuli@example.com
ssh: Could not resolve hostname example.com:2222: Name or service not known
SSH handshake failed.
$ et -s="ssh -p 2222 mbtamuli@example.com" mbtamuli@example.com
ssh: Could not resolve hostname ssh: Name or service not known
SSH handshake failed.
$ et -s="ssh -p 2222" mbtamuli@example.com
ssh: Could not resolve hostname ssh: Name or service not known
SSH handshake failed.
$ et -s="-p 2222" mbtamuli@example.com
ssh: Could not resolve hostname /bin/bash: Name or service not known
SSH handshake failed.
$ et -s="2222" mbtamuli@example.com
ssh: connect to host 2222 port 22: Invalid argument
SSH handshake failed.
```

**Comment by MisterTea** [comment]
You circumnavigated the right answer, but here's how to do it.  This works for me (I run ET on port 8080):

```
et -s="-p 22 example.com" example.com:8080
```

What would make this easier?  Maybe I should have people also put the 'ssh' in the beginning and provide an example in the help?

Would you be willing to edit this file and add some relevant documentation in a pull request once you get it working?  https://github.com/MisterTea/EternalTCP/blob/master/launcher/et

Thanks!

**Comment by mbtamuli** [comment]
I was thinking about adding example in the [Usage Section](https://mistertea.github.io/EternalTCP/usermanual/#using)

**Comment by MisterTea** [comment]
That's a good idea.  Here's what you need to edit to change the usage section: https://github.com/MisterTea/EternalTCP/blob/gh-pages/usermanual.md

I think an example in the launcher help would be good as well.  Thanks a lot!

**Comment by mbtamuli** [comment]
@MisterTea If you want the examples to be worded differently, do tell.

**Comment by MisterTea** [comment]
Thanks!!!
