### ISSUE TITLE
Missing XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by tfg13** [MisterTea/EternalTCP#51]
(as discussed)

``` bash
ssh $SERVER
$ echo $XDG_RUNTIME_DIR
/run/user/12345
```
but

```bash
et $SERVER
$ echo $XDG_RUNTIME_DIR

```

This var should have been set by (I think) `logind` and fundamental things like `systemctl --user` depend on it.

**Comment by MisterTea** [comment]
Got it.  It turns out PAM is not being initialized correctly.  I should have a fix within the week.

**Comment by MisterTea** [comment]
Ugh, actually PAM is a huge pain.  Getting some error about account already being in a session, and PAM requires some interactivity.  Going to have to look into other ways to handle this

**Comment by MisterTea** [comment]
This should be fixed in latest master.
