### ISSUE TITLE
fish shell prompt invisible

### ISSUE THREAD

**Issue by daniel-centore** [MisterTea/EternalTCP#56]
The shell prompt for fish is invisible in the new version
![screen shot 2017-07-25 at 4 09 52 pm](https://user-images.githubusercontent.com/569864/28597618-bdf2bb36-7153-11e7-916b-988459d8fb36.png)

How it should look:
![screen shot 2017-07-25 at 4 09 59 pm](https://user-images.githubusercontent.com/569864/28597622-c2f78dc8-7153-11e7-8fd1-cf6dc72e3425.png)

**Comment by MisterTea** [comment]
Fixed in e098c2a189f3dd98f0d66f806d1bdab28f02283d
