### ISSUE TITLE
BSD/POSIXish compatibility

### ISSUE THREAD

**Issue by MakeItGreatAgain** [MisterTea/EternalTCP#62]
I have ported et to OpenBSD (which needed a few changes), but noticed some Linuxisms in the et launcher client script which break POSIX compatibility can easily be worked around by using standardized options (rather than GNU extensions), in particular, the launcher script uses "head -c" and "/bin/bash" on the remote, which are not UNIX standards. 

This is easily fixed by replacing "/bin/bash" with "/bin/sh" (tested to be fine with OpenBSD ksh, at least) on line 114 (which sets SSH_OUTPUT)  and by replacing head -c with "dd bs=1 count=N 2>/dev/null" in the PASSKEY_GENERATOR and ID_GENERATOR assignments.  

Also, the UNIX standards only seem to require "/dev/null and /dev/console" so you cannot rely on the presence of /dev/urandom, and it is my understanding that using tr to strip non-printable characters may result in weakening the keys.  It may be be safer and certainly more portable to include a CSPRNG and use a hash of the output or offer a fallback to egd.  I've not done this as all systems I have available to me have /dev/urandom available.  

I will clean up my changes soon and provide you the OpenBSD diff later.

**Comment by MisterTea** [comment]
Cool!  Looking forward to seeing the pull request.

**Comment by MisterTea** [comment]
@MakeItGreatAgain Any update?

**Comment by MakeItGreatAgain** [comment]
Sorry - I have been busy and you update quickly :)  I will try to get you proper port in a week or two - I am still using it myself
