### ISSUE TITLE
etserver crashing on std:bad_alloc

### ISSUE THREAD

**Issue by burgalon** [MisterTea/EternalTCP#66]
ETserver 4.0.4 running on Ubuntu 16.04 and etclient 4.0.5 on OSX.

```
E1009 22:42:25.246457 16703 Connection.cpp:101] Tried to close a dead socket
E1009 22:46:45.436381 16703 Connection.cpp:101] Tried to close a dead socket
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by MisterTea** [comment]
what command did you use?

**Comment by burgalon** [comment]
i'm using regular connect `et username@server` and usually connected with `tmux -CC a`.
After a night it would usually crash

**Comment by MisterTea** [comment]
Looks like a memory leak.  Can you get a stack trace where the exception is thrown?  Also can you watch the memory usage and see whether it's creeping up?

**Comment by burgalon** [comment]
how can I make the etserver output stack trace?

**Comment by MisterTea** [comment]
Is that crash happening on the client or server?

**Comment by burgalon** [comment]
server

**Comment by MisterTea** [comment]
Can you try running the server under gdb? On the actual machine (or in a mosh server):

```
sudo systemctl stop et
sudo gdb -ex run --args etserver
```

That will run etserver inside gdb.  Then when it crashes, you'll be able to type `bt -a` and get a backtrace

**Comment by burgalon** [comment]
it's possible that the bad_alloc, was actually caused by the OS running out of memory... I'm still trying to figure this out

**Comment by MisterTea** [comment]
Closing since the issue was OOM on the machine
