### ISSUE TITLE
Etclient crashes (cannot reproduce)

### ISSUE THREAD

**Issue by DmitryKoterov** [MisterTea/EternalTCP#71]
This is hard to reproduce. 

After some significant interval with no internet, et port forwarding process sometimes crashes:

*** Check failure stack trace: ***
    @        0x104f0f0ce  google::LogMessage::Fail()
    @        0x104f0e3ad  google::LogMessage::SendToLog()
    @        0x104f0eab3  google::LogMessage::Flush()
    @        0x104f11d03  google::LogMessageFatal::~LogMessageFatal()
    @        0x104f0f3b7  google::LogMessageFatal::~LogMessageFatal()
    @        0x104cb564d  et::UnixSocketHandler::initSocket()
    @        0x104cb66f5  et::UnixSocketHandler::accept()
    @        0x104ca4404  et::PortForwardClientListener::listen()
    @        0x104ca3394  et::PortForwardClientRouter::update()
    @        0x104c9f6e3  main
    @     0x7fff73c04145  start
    @                0x4  (unknown)

In /tmp/etclient_err:

F1104 13:07:28.042229 2905396032 UnixSocketHandler.cpp:380] Error: (22): Invalid argument
117

**Comment by DmitryKoterov** [comment]
...this happens immediately after internet connection is restored back. But very hard to reproduce

**Comment by ailzhang** [comment]
I can't seem to reproduce this on my side. Please share your log files next time it happens. Thanks!

**Comment by DmitryKoterov** [comment]
Here are some more samples (same usecase - kept running, Mac slept, then woken up after ~12h):

  *** Check failure stack trace: ***
    @        0x1021fb0ce  google::LogMessage::Fail()
    @        0x1021fa3ad  google::LogMessage::SendToLog()
    @        0x1021faab3  google::LogMessage::Flush()
    @        0x1021fdd03  google::LogMessageFatal::~LogMessageFatal()
    @        0x1021fb3b7  google::LogMessageFatal::~LogMessageFatal()
    @        0x101f8a6b5  et::UnixSocketHandler::initSocket()
    @        0x101f8b7bd  et::UnixSocketHandler::accept()
    @        0x101f79e69  et::PortForwardClientListener::listen()
    @        0x101f78f54  et::PortForwardClientRouter::update()
    @        0x101f76b29  main
    @     0x7fffe9b34235  start

In /tmp/etclient_err:

  E1117 09:06:31.677979 4070904768 PortForwardClientListener.cpp:94] Tried to write to a socket that no longer exists!
  E1117 09:07:01.308543 4070904768 PortForwardClientListener.cpp:94] Tried to write to a socket that no longer exists!
  E1117 09:07:01.321117 4070904768 PortForwardClientListener.cpp:94] Tried to write to a socket that no longer exists!
  E1117 09:07:01.332490 4070904768 PortForwardClientListener.cpp:94] Tried to write to a socket that no longer exists!
  E1117 09:07:01.332545 4070904768 PortForwardClientListener.cpp:94] Tried to write to a socket that no longer exists!
  E1117 09:07:01.344841 4070904768 PortForwardClientListener.cpp:94] Tried to write to a socket that no longer exists!
  E1117 09:07:25.522713 4070904768 PortForwardClientListener.cpp:94] Tried to write to a socket that no longer exists!

**Comment by DmitryKoterov** [comment]
Also one more time it threw this exception (after 1d of no connection), in /tmp/etclient_err:

E1119 20:54:00.383008 3077604288 UnixSocketHandler.cpp:45] Error reading: 54 Connection reset by peer
F1119 20:54:00.384682 3077604288 UnixSocketHandler.cpp:380] Error: (22): Invalid argument

**Comment by MisterTea** [comment]
Hmm, you are failing inside initsocket, weird.  I can add a guard to handle that case, but can you tell me what OS the client & server are running?  I'm really surprised setsocketopt is failing for you.

**Comment by MisterTea** [comment]
Hmm, these people are having the same issue: https://github.com/joyent/illumos-joyent/issues/148

**Comment by MisterTea** [comment]
Alright I added a guard around initSocket.  If you still have this issue,  reply here and we will re-open.

**Comment by mcybz** [comment]
I have this issue running clear linux

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/83850054/119277394-6ae57d00-bbed-11eb-978b-e568c656fab0.png">
