### ISSUE TITLE
SSH config port not being used

### ISSUE THREAD

**Issue by daniel-centore** [MisterTea/EternalTCP#73]
Here is my `~/.ssh/config` file:
```
Host bfs
    HostName 127.0.0.1
    User daniel
    Port 2044
```

When I ssh using `ssh bfs`, it allows me to connect.

When I use et, I get this instead:
```
dcentore@Danylo-MBP17 ~> et bfs
ssh: connect to host 127.0.0.1 port 22: Connection refused
Error:  The Eternal Terminal daemon is not running.  Please (re)start the et daemon on the server.
dcentore@Danylo-MBP17 ~>
```

It does not seem to be respecting the port I put in the config file, as it's clearly trying to connect with 22. However, the config file _is_ being used, because if I change the `HostName` to something else, the hostname in the aforementioned `et` output also changes.

**Comment by ailzhang** [comment]
Hi Daniel,

I tried on my local mac and the port setting was used. Could you please try `et daniel@bfs` and paste the $TMPDIR/et.INFO here?

**Comment by daniel-centore** [comment]
`$TMPDIR/et.INFO`:
```
Log file created at: 2017/11/26 21:44:46
Running on machine: Danylo-MBP17.local
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1126 21:44:46.517520 3953152960 TerminalClient.cpp:184] Parsed ssh config file, connecting to localhost
```

**Comment by daniel-centore** [comment]
I'm not sure if this helps you debug, but the problem persists even when removing the entry from my user config and adding the same entry to `/etc/ssh/ssh_config`. `ssh daniel@bfs` continues to work properly in this case.

**Comment by ailzhang** [comment]
Hi Daniel,

Thanks for the information! To clarify, did you mean that `ssh bfs` didn't work but `ssh daniel@bfs` worked?

**Comment by daniel-centore** [comment]
`ssh bfs` works and `ssh daniel@bfs` works, sorry for the confusion. Regardless of which config file I use the output is identical, and regardless of whether or not I include my username in either command, the output is identical.

```
dcentore@Danylo-MBP17 ~> ssh daniel@bfs
ssh: connect to host localhost port 2044: Connection refused
dcentore@Danylo-MBP17 ~> ssh bfs
ssh: connect to host localhost port 2044: Connection refused
dcentore@Danylo-MBP17 ~> et daniel@bfs
ssh: connect to host localhost port 22: Connection refused
Error:  The Eternal Terminal daemon is not running.  Please (re)start the et daemon on the server.
dcentore@Danylo-MBP17 ~> et bfs
ssh: connect to host localhost port 22: Connection refused
Error:  The Eternal Terminal daemon is not running.  Please (re)start the et daemon on the server.
```

**Comment by ailzhang** [comment]
Hi Daniel,

This is indeed a bug in the code. We sshed to the parsed hostname directly, which should be `bfs` in this case to make use of the ssh config file. This has been fixed here https://github.com/MisterTea/EternalTCP/commit/1dd2209950eab92fdbaa5d292cbc027d3ef212d9. Thanks for bringing this to our attention!

**Comment by daniel-centore** [comment]
Thank you!
