### ISSUE TITLE
Entering an invalid idpasskey can crash the server

### ISSUE THREAD

**Issue by coventry** [MisterTea/EternalTCP#79]
I really like where EternalTCP is heading.

It would be considerate to add warnings to the `README` and other documentation that `etserver` can easily be induced to segfault, and is therefore a likely security vulnerability and should not be used in sensitive contexts.

**Comment by MisterTea** [comment]
Can you be more specific?  If there is a segfault that can be induced, I would rather fix it than put up some disclaimer.

**Comment by MisterTea** [comment]
Just to be clear: if someone sends raw data using telnet, it is possible to segfault because ET will try to make an impossibly large malloc.  This isn't a security bug, but it is annoying because it crashes the main server which disconnects all other sessions.  A fix is on the way.

**Comment by coventry** [comment]
Please reconsider this approach. A segfault on corrupted inputs is *ipso facto* a security vulnerability in a network application. A facile check for the specific corruption I provided is an inadequate response.

I wasn't even auditing for vulnerabilities, just stumbled on it by accident while debugging the connection.
