### ISSUE TITLE
Add flag to kill et previous sessions before login

### ISSUE THREAD

**Issue by MisterTea** [MisterTea/EternalTCP#81]
Consider adding a flag that kills all etserver processes from the current user before login.  This removes the need to manually clean up stale processes assuming that each user will have a single session.

**Comment by ailzhang** [comment]
This is a brilliant idea!! I'm happy take care of this :)

**Comment by ocavue** [comment]
It's exactly what I need!

**Comment by MisterTea** [comment]
In latest master.
